version: '3'
services:
    iris:
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
          - 1972:1972         
          - 52773:52773         
        volumes:
          - "./:/datavol"


