version: '3'
services:
    iris:
        build: 
          context: .
          dockerfile: Dockerfile
        restart: always
        command: --ISCAgent false          
        ports:
          - 1972:1972
          - 52773:52773         
        volumes:
          - "./:/datavol"


