version: '3'
services:
    iris:
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
          - 52773:52773
          - 51773:51773        
        volumes:
          - ./:/datavol


